language: python
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.3
      - python3.5
      - python3.6
      - python3.7
      - python3.8
env:
  - TOXENV=py27-django-17
  - TOXENV=py27-django-18
  - TOXENV=py27-django-19
  - TOXENV=py27-django-110
  - TOXENV=py27-django-111
  - TOXENV=py33-django-17
  - TOXENV=py33-django-18
  - TOXENV=py34-django-17
  - TOXENV=py34-django-18
  - TOXENV=py34-django-19
  - TOXENV=py34-django-110
  - TOXENV=py34-django-111
  - TOXENV=py34-django-20
  - TOXENV=py35-django-19
  - TOXENV=py35-django-110
  - TOXENV=py35-django-111
  - TOXENV=py35-django-20
  - TOXENV=py35-django-21
  - TOXENV=py35-django-22
  - TOXENV=py36-django-111
  - TOXENV=py36-django-20
  - TOXENV=py36-django-21
  - TOXENV=py36-django-22
  - TOXENV=py36-django-30
  - TOXENV=py36-django-31
  - TOXENV=py36-django-master
  - TOXENV=py37-django-21
  - TOXENV=py37-django-22
  - TOXENV=py37-django-30
  - TOXENV=py37-django-31
  - TOXENV=py38-django-22
  - TOXENV=py38-django-30
  - TOXENV=py38-django-31
matrix:
  fast_finish: true
  allow_failures:
    - env: TOXENV=py36-django-master
    - env: TOXENV=py37-django-master
    - env: TOXENV=py38-django-master
install:
    - pip install tox
script:
  - tox
