# per https://www.appveyor.com/docs/lang/python/

build: off

environment:
  matrix:
    - TOXENV: py35-django-19
    - TOXENV: py35-django-110
    - TOXENV: py35-django-111
    - TOXENV: py35-django-20
    - TOXENV: py35-django-21
    - TOXENV: py35-django-22
    - TOXENV: py36-django-111
    - TOXENV: py36-django-20
    - TOXENV: py36-django-21
    - TOXENV: py36-django-22
    - TOXENV: py36-django-30
    - TOXENV: py36-django-31
    - TOXENV: py36-django-master
    - TOXENV: py37-django-21
    - TOXENV: py37-django-22
    - TOXENV: py37-django-30
    - TOXENV: py37-django-31
    - TOXENV: py37-django-master

matrix:
  allow_failures:
    - TOXENV: py36-django-master
    - TOXENV: py37-django-master

install:
  - pip install tox

test_script:
  - ver
  - tox

